//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.Web.Services.WebServiceAttribute(Namespace="http://tempuri.org/")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_WebSrviTrg", Namespace="http://tempuri.org/")]
public abstract partial class WebServiceContract : System.Web.Services.WebService {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/WebSrviTrg/ExecuteTrigger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
    public abstract int ExecuteTrigger(string text, bool wait, out string errorText);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/WebSrviTrg/ExecuteTriggerWithResponse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
    public abstract int ExecuteTriggerWithResponse(string text, bool wait, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] out byte[] responseData, out string errorText);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/WebSrviTrg/ExecuteTriggerAndSetVariables", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
    public abstract int ExecuteTriggerAndSetVariables(string text, string variableData, bool wait, out string errorText);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/WebSrviTrg/ExecuteTriggerAndSetVariablesWithResponse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/")]
    public abstract int ExecuteTriggerAndSetVariablesWithResponse(string text, string variableData, bool wait, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] out byte[] responseData, out string errorText);
}
