//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InforConnectorLibrary.InforUnplannedMaterial {
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetailMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIndexField;
        
        private string messageCodeField;
        
        private MessageMessageType messageTypeField;
        
        private string messageTextField;
        
        private string messageSourceField;
        
        private DetailMessage[] messageDetailsField;
        
        private string messageCorrectiveActionField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private MessageMessageReference messageReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string messageIndex {
            get {
                return this.messageIndexField;
            }
            set {
                this.messageIndexField = value;
                this.RaisePropertyChanged("messageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("messageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public MessageMessageType messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("messageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string messageSource {
            get {
                return this.messageSourceField;
            }
            set {
                this.messageSourceField = value;
                this.RaisePropertyChanged("messageSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DetailMessage[] MessageDetails {
            get {
                return this.messageDetailsField;
            }
            set {
                this.messageDetailsField = value;
                this.RaisePropertyChanged("MessageDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string messageCorrectiveAction {
            get {
                return this.messageCorrectiveActionField;
            }
            set {
                this.messageCorrectiveActionField = value;
                this.RaisePropertyChanged("messageCorrectiveAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageAdditionalHelpText", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("messageAdditionalHelpURI", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=7)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public MessageMessageReference MessageReference {
            get {
                return this.messageReferenceField;
            }
            set {
                this.messageReferenceField = value;
                this.RaisePropertyChanged("MessageReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public enum MessageMessageType {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Information,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class DetailMessage : Message {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":messageAdditionalHelpText")]
        messageAdditionalHelpText,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":messageAdditionalHelpURI")]
        messageAdditionalHelpURI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class MessageMessageReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageReferenceTypeField;
        
        private object messageReferenceInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageReferenceType {
            get {
                return this.messageReferenceTypeField;
            }
            set {
                this.messageReferenceTypeField = value;
                this.RaisePropertyChanged("messageReferenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object messageReferenceInfo {
            get {
                return this.messageReferenceInfoField;
            }
            set {
                this.messageReferenceInfoField = value;
                this.RaisePropertyChanged("messageReferenceInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class EmptyValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class ComparisonExpressionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ComparisonExpressionTypeComparisonOperator comparisonOperatorField;
        
        private object itemField;
        
        private object item1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComparisonExpressionTypeComparisonOperator comparisonOperator {
            get {
                return this.comparisonOperatorField;
            }
            set {
                this.comparisonOperatorField = value;
                this.RaisePropertyChanged("comparisonOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributeName", typeof(filterAttributeListDT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("emptyValue", typeof(EmptyValueType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("instanceValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributeName", typeof(filterAttributeListDT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("emptyValue", typeof(EmptyValueType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("instanceValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public enum ComparisonExpressionTypeComparisonOperator {
        
        /// <remarks/>
        le,
        
        /// <remarks/>
        lt,
        
        /// <remarks/>
        ge,
        
        /// <remarks/>
        gt,
        
        /// <remarks/>
        ne,
        
        /// <remarks/>
        eq,
        
        /// <remarks/>
        like,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public enum filterAttributeListDT {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.ProdOrder")]
        IWMStdUnplannedMatlIssueProdOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Operation")]
        IWMStdUnplannedMatlIssueOperation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Item")]
        IWMStdUnplannedMatlIssueItem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Warehouse")]
        IWMStdUnplannedMatlIssueWarehouse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Location")]
        IWMStdUnplannedMatlIssueLocation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.LotCode")]
        IWMStdUnplannedMatlIssueLotCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.InvDate")]
        IWMStdUnplannedMatlIssueInvDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.SerialNumber")]
        IWMStdUnplannedMatlIssueSerialNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Quantity")]
        IWMStdUnplannedMatlIssueQuantity,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Unit")]
        IWMStdUnplannedMatlIssueUnit,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.Position")]
        IWMStdUnplannedMatlIssuePosition,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.HandlingUnit")]
        IWMStdUnplannedMatlIssueHandlingUnit,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.CreateTargetHU")]
        IWMStdUnplannedMatlIssueCreateTargetHU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.TargetHU")]
        IWMStdUnplannedMatlIssueTargetHU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.GenerateOutbound")]
        IWMStdUnplannedMatlIssueGenerateOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.ReleaseOutbound")]
        IWMStdUnplannedMatlIssueReleaseOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.TransID")]
        IWMStdUnplannedMatlIssueTransID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.LoginCode")]
        IWMStdUnplannedMatlIssueLoginCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.PrintLabel")]
        IWMStdUnplannedMatlIssuePrintLabel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.OutData")]
        IWMStdUnplannedMatlIssueOutData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.RunNumber")]
        IWMStdUnplannedMatlIssueRunNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.AllSerials")]
        IWMStdUnplannedMatlIssueAllSerials,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.GenerateSerials")]
        IWMStdUnplannedMatlIssueGenerateSerials,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.AllNinvLots")]
        IWMStdUnplannedMatlIssueAllNinvLots,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdUnplannedMatlIssue.GenerateNinvLots")]
        IWMStdUnplannedMatlIssueGenerateNinvLots,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class LogicalExpressionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LogicalExpressionTypeLogicalOperator logicalOperatorField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LogicalExpressionTypeLogicalOperator logicalOperator {
            get {
                return this.logicalOperatorField;
            }
            set {
                this.logicalOperatorField = value;
                this.RaisePropertyChanged("logicalOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparisonExpression", typeof(ComparisonExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalExpression", typeof(LogicalExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public enum LogicalExpressionTypeLogicalOperator {
        
        /// <remarks/>
        or,
        
        /// <remarks/>
        and,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class FilterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparisonExpression", typeof(ComparisonExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalExpression", typeof(LogicalExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class ActivationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private int companyField;
        
        private bool companyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool companySpecified {
            get {
                return this.companyFieldSpecified;
            }
            set {
                this.companyFieldSpecified = value;
                this.RaisePropertyChanged("companySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class IssueMaterialResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IssueMaterialResponseTypeIWMStdUnplannedMatlIssue[] dataAreaField;
        
        private InformationMessage[] informationAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IWMStdUnplannedMatlIssue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IssueMaterialResponseTypeIWMStdUnplannedMatlIssue[] DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
                this.RaisePropertyChanged("DataArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InformationMessage[] InformationArea {
            get {
                return this.informationAreaField;
            }
            set {
                this.informationAreaField = value;
                this.RaisePropertyChanged("InformationArea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class IssueMaterialResponseTypeIWMStdUnplannedMatlIssue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string outDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OutData {
            get {
                return this.outDataField;
            }
            set {
                this.outDataField = value;
                this.RaisePropertyChanged("OutData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class InformationMessage : Message {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class IssueMaterialRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IssueMaterialRequestTypeControlArea controlAreaField;
        
        private IssueMaterialRequestTypeIWMStdUnplannedMatlIssue[] dataAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public IssueMaterialRequestTypeControlArea ControlArea {
            get {
                return this.controlAreaField;
            }
            set {
                this.controlAreaField = value;
                this.RaisePropertyChanged("ControlArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IWMStdUnplannedMatlIssue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public IssueMaterialRequestTypeIWMStdUnplannedMatlIssue[] DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
                this.RaisePropertyChanged("DataArea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class IssueMaterialRequestTypeControlArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private processingScope processingScopeField;
        
        public IssueMaterialRequestTypeControlArea() {
            this.processingScopeField = processingScope.request;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute(processingScope.request)]
        public processingScope processingScope {
            get {
                return this.processingScopeField;
            }
            set {
                this.processingScopeField = value;
                this.RaisePropertyChanged("processingScope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public enum processingScope {
        
        /// <remarks/>
        not_applicable,
        
        /// <remarks/>
        request,
        
        /// <remarks/>
        business_entity,
        
        /// <remarks/>
        business_entity_component,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
    public partial class IssueMaterialRequestTypeIWMStdUnplannedMatlIssue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prodOrderField;
        
        private long operationField;
        
        private bool operationFieldSpecified;
        
        private string itemField;
        
        private string warehouseField;
        
        private string locationField;
        
        private string lotCodeField;
        
        private string invDateField;
        
        private string serialNumberField;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        private string unitField;
        
        private long positionField;
        
        private bool positionFieldSpecified;
        
        private string handlingUnitField;
        
        private string createTargetHUField;
        
        private string targetHUField;
        
        private string generateOutboundField;
        
        private string releaseOutboundField;
        
        private string transIDField;
        
        private string loginCodeField;
        
        private string printLabelField;
        
        private string runNumberField;
        
        private string allSerialsField;
        
        private string generateSerialsField;
        
        private string allNinvLotsField;
        
        private string generateNinvLotsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ProdOrder {
            get {
                return this.prodOrderField;
            }
            set {
                this.prodOrderField = value;
                this.RaisePropertyChanged("ProdOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationSpecified {
            get {
                return this.operationFieldSpecified;
            }
            set {
                this.operationFieldSpecified = value;
                this.RaisePropertyChanged("OperationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
                this.RaisePropertyChanged("Warehouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LotCode {
            get {
                return this.lotCodeField;
            }
            set {
                this.lotCodeField = value;
                this.RaisePropertyChanged("LotCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string InvDate {
            get {
                return this.invDateField;
            }
            set {
                this.invDateField = value;
                this.RaisePropertyChanged("InvDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PositionSpecified {
            get {
                return this.positionFieldSpecified;
            }
            set {
                this.positionFieldSpecified = value;
                this.RaisePropertyChanged("PositionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string HandlingUnit {
            get {
                return this.handlingUnitField;
            }
            set {
                this.handlingUnitField = value;
                this.RaisePropertyChanged("HandlingUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CreateTargetHU {
            get {
                return this.createTargetHUField;
            }
            set {
                this.createTargetHUField = value;
                this.RaisePropertyChanged("CreateTargetHU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string TargetHU {
            get {
                return this.targetHUField;
            }
            set {
                this.targetHUField = value;
                this.RaisePropertyChanged("TargetHU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string GenerateOutbound {
            get {
                return this.generateOutboundField;
            }
            set {
                this.generateOutboundField = value;
                this.RaisePropertyChanged("GenerateOutbound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ReleaseOutbound {
            get {
                return this.releaseOutboundField;
            }
            set {
                this.releaseOutboundField = value;
                this.RaisePropertyChanged("ReleaseOutbound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
                this.RaisePropertyChanged("TransID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string LoginCode {
            get {
                return this.loginCodeField;
            }
            set {
                this.loginCodeField = value;
                this.RaisePropertyChanged("LoginCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string PrintLabel {
            get {
                return this.printLabelField;
            }
            set {
                this.printLabelField = value;
                this.RaisePropertyChanged("PrintLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string RunNumber {
            get {
                return this.runNumberField;
            }
            set {
                this.runNumberField = value;
                this.RaisePropertyChanged("RunNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string AllSerials {
            get {
                return this.allSerialsField;
            }
            set {
                this.allSerialsField = value;
                this.RaisePropertyChanged("AllSerials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string GenerateSerials {
            get {
                return this.generateSerialsField;
            }
            set {
                this.generateSerialsField = value;
                this.RaisePropertyChanged("GenerateSerials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string AllNinvLots {
            get {
                return this.allNinvLotsField;
            }
            set {
                this.allNinvLotsField = value;
                this.RaisePropertyChanged("AllNinvLots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string GenerateNinvLots {
            get {
                return this.generateNinvLotsField;
            }
            set {
                this.generateNinvLotsField = value;
                this.RaisePropertyChanged("GenerateNinvLots");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue", ConfigurationName="InforUnplannedMaterial.IWMStdUnplannedMatlIssue")]
    public interface IWMStdUnplannedMatlIssue {
        
        // CODEGEN: Generating message contract since message IssueMaterialRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(InforConnectorLibrary.InforUnplannedMaterial.Message), Action="", Name="Result")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActivationType))]
        InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponse IssueMaterial(InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponse> IssueMaterialAsync(InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IssueMaterial", WrapperNamespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue", IsWrapped=true)]
    public partial class IssueMaterialRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue")]
        public InforConnectorLibrary.InforUnplannedMaterial.ActivationType Activation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueMaterialRequest", Namespace="", Order=0)]
        public InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequestType IssueMaterialRequest1;
        
        public IssueMaterialRequest() {
        }
        
        public IssueMaterialRequest(InforConnectorLibrary.InforUnplannedMaterial.ActivationType Activation, InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequestType IssueMaterialRequest1) {
            this.Activation = Activation;
            this.IssueMaterialRequest1 = IssueMaterialRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IssueMaterialResponse", WrapperNamespace="http://www.infor.com/businessinterface/IWMStdUnplannedMatlIssue", IsWrapped=true)]
    public partial class IssueMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueMaterialResponse", Namespace="", Order=0)]
        public InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponseType IssueMaterialResponse1;
        
        public IssueMaterialResponse() {
        }
        
        public IssueMaterialResponse(InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponseType IssueMaterialResponse1) {
            this.IssueMaterialResponse1 = IssueMaterialResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWMStdUnplannedMatlIssueChannel : InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMStdUnplannedMatlIssueClient : System.ServiceModel.ClientBase<InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue>, InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue {
        
        public WMStdUnplannedMatlIssueClient() {
        }
        
        public WMStdUnplannedMatlIssueClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMStdUnplannedMatlIssueClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMStdUnplannedMatlIssueClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMStdUnplannedMatlIssueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponse InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue.IssueMaterial(InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest request) {
            return base.Channel.IssueMaterial(request);
        }
        
        public InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponseType IssueMaterial(InforConnectorLibrary.InforUnplannedMaterial.ActivationType Activation, InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequestType IssueMaterialRequest1) {
            InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest inValue = new InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest();
            inValue.Activation = Activation;
            inValue.IssueMaterialRequest1 = IssueMaterialRequest1;
            InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponse retVal = ((InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue)(this)).IssueMaterial(inValue);
            return retVal.IssueMaterialResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponse> InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue.IssueMaterialAsync(InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest request) {
            return base.Channel.IssueMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialResponse> IssueMaterialAsync(InforConnectorLibrary.InforUnplannedMaterial.ActivationType Activation, InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequestType IssueMaterialRequest1) {
            InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest inValue = new InforConnectorLibrary.InforUnplannedMaterial.IssueMaterialRequest();
            inValue.Activation = Activation;
            inValue.IssueMaterialRequest1 = IssueMaterialRequest1;
            return ((InforConnectorLibrary.InforUnplannedMaterial.IWMStdUnplannedMatlIssue)(this)).IssueMaterialAsync(inValue);
        }
    }
}
