//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InforConnector.InforProducedQuantity {
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetailMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIndexField;
        
        private string messageCodeField;
        
        private MessageMessageType messageTypeField;
        
        private string messageTextField;
        
        private string messageSourceField;
        
        private DetailMessage[] messageDetailsField;
        
        private string messageCorrectiveActionField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private MessageMessageReference messageReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string messageIndex {
            get {
                return this.messageIndexField;
            }
            set {
                this.messageIndexField = value;
                this.RaisePropertyChanged("messageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("messageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public MessageMessageType messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("messageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string messageSource {
            get {
                return this.messageSourceField;
            }
            set {
                this.messageSourceField = value;
                this.RaisePropertyChanged("messageSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DetailMessage[] MessageDetails {
            get {
                return this.messageDetailsField;
            }
            set {
                this.messageDetailsField = value;
                this.RaisePropertyChanged("MessageDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string messageCorrectiveAction {
            get {
                return this.messageCorrectiveActionField;
            }
            set {
                this.messageCorrectiveActionField = value;
                this.RaisePropertyChanged("messageCorrectiveAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageAdditionalHelpText", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("messageAdditionalHelpURI", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=7)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public MessageMessageReference MessageReference {
            get {
                return this.messageReferenceField;
            }
            set {
                this.messageReferenceField = value;
                this.RaisePropertyChanged("MessageReference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public enum MessageMessageType {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Information,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class DetailMessage : Message {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":messageAdditionalHelpText")]
        messageAdditionalHelpText,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":messageAdditionalHelpURI")]
        messageAdditionalHelpURI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class MessageMessageReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageReferenceTypeField;
        
        private object messageReferenceInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageReferenceType {
            get {
                return this.messageReferenceTypeField;
            }
            set {
                this.messageReferenceTypeField = value;
                this.RaisePropertyChanged("messageReferenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object messageReferenceInfo {
            get {
                return this.messageReferenceInfoField;
            }
            set {
                this.messageReferenceInfoField = value;
                this.RaisePropertyChanged("messageReferenceInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class EmptyValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ComparisonExpressionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ComparisonExpressionTypeComparisonOperator comparisonOperatorField;
        
        private object itemField;
        
        private object item1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComparisonExpressionTypeComparisonOperator comparisonOperator {
            get {
                return this.comparisonOperatorField;
            }
            set {
                this.comparisonOperatorField = value;
                this.RaisePropertyChanged("comparisonOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributeName", typeof(filterAttributeListDT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("emptyValue", typeof(EmptyValueType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("instanceValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributeName", typeof(filterAttributeListDT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("emptyValue", typeof(EmptyValueType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("instanceValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public enum ComparisonExpressionTypeComparisonOperator {
        
        /// <remarks/>
        le,
        
        /// <remarks/>
        lt,
        
        /// <remarks/>
        ge,
        
        /// <remarks/>
        gt,
        
        /// <remarks/>
        ne,
        
        /// <remarks/>
        eq,
        
        /// <remarks/>
        like,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public enum filterAttributeListDT {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ProductionOrder")]
        IWMStdReportProductionProductionOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.QtyDeliver")]
        IWMStdReportProductionQtyDeliver,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.QtyReject")]
        IWMStdReportProductionQtyReject,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Warehouse")]
        IWMStdReportProductionWarehouse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.LotCode")]
        IWMStdReportProductionLotCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.PostHours")]
        IWMStdReportProductionPostHours,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReportMore")]
        IWMStdReportProductionReportMore,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReportPrevious")]
        IWMStdReportProductionReportPrevious,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.BackFlush")]
        IWMStdReportProductionBackFlush,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.DirectReceipt")]
        IWMStdReportProductionDirectReceipt,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Complete")]
        IWMStdReportProductionComplete,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.SerialNumber")]
        IWMStdReportProductionSerialNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.GenerateInbound")]
        IWMStdReportProductionGenerateInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReleaseInbound")]
        IWMStdReportProductionReleaseInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.RunNumber")]
        IWMStdReportProductionRunNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Location")]
        IWMStdReportProductionLocation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.InsertNewSerial")]
        IWMStdReportProductionInsertNewSerial,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Shift")]
        IWMStdReportProductionShift,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReceiptLocation")]
        IWMStdReportProductionReceiptLocation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.CompletionDate")]
        IWMStdReportProductionCompletionDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.KanbanID")]
        IWMStdReportProductionKanbanID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.RejectReason")]
        IWMStdReportProductionRejectReason,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.TransID")]
        IWMStdReportProductionTransID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.GenerateHU")]
        IWMStdReportProductionGenerateHU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.HandlingUnit")]
        IWMStdReportProductionHandlingUnit,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.FromRepOperation")]
        IWMStdReportProductionFromRepOperation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.CrossdockEnabled")]
        IWMStdReportProductionCrossdockEnabled,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.LoginCode")]
        IWMStdReportProductionLoginCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.OutData")]
        IWMStdReportProductionOutData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.PackageDef")]
        IWMStdReportProductionPackageDef,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class LogicalExpressionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LogicalExpressionTypeLogicalOperator logicalOperatorField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LogicalExpressionTypeLogicalOperator logicalOperator {
            get {
                return this.logicalOperatorField;
            }
            set {
                this.logicalOperatorField = value;
                this.RaisePropertyChanged("logicalOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparisonExpression", typeof(ComparisonExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalExpression", typeof(LogicalExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public enum LogicalExpressionTypeLogicalOperator {
        
        /// <remarks/>
        or,
        
        /// <remarks/>
        and,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class FilterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparisonExpression", typeof(ComparisonExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LogicalExpression", typeof(LogicalExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ActivationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private int companyField;
        
        private bool companyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool companySpecified {
            get {
                return this.companyFieldSpecified;
            }
            set {
                this.companyFieldSpecified = value;
                this.RaisePropertyChanged("companySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ReportProductionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReportProductionResponseTypeIWMStdReportProduction[] dataAreaField;
        
        private InformationMessage[] informationAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IWMStdReportProduction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ReportProductionResponseTypeIWMStdReportProduction[] DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
                this.RaisePropertyChanged("DataArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InformationMessage[] InformationArea {
            get {
                return this.informationAreaField;
            }
            set {
                this.informationAreaField = value;
                this.RaisePropertyChanged("InformationArea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ReportProductionResponseTypeIWMStdReportProduction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string outDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OutData {
            get {
                return this.outDataField;
            }
            set {
                this.outDataField = value;
                this.RaisePropertyChanged("OutData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class InformationMessage : Message {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ReportProductionRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReportProductionRequestTypeControlArea controlAreaField;
        
        private ReportProductionRequestTypeIWMStdReportProduction[] dataAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ReportProductionRequestTypeControlArea ControlArea {
            get {
                return this.controlAreaField;
            }
            set {
                this.controlAreaField = value;
                this.RaisePropertyChanged("ControlArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IWMStdReportProduction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ReportProductionRequestTypeIWMStdReportProduction[] DataArea {
            get {
                return this.dataAreaField;
            }
            set {
                this.dataAreaField = value;
                this.RaisePropertyChanged("DataArea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ReportProductionRequestTypeControlArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private processingScope processingScopeField;
        
        public ReportProductionRequestTypeControlArea() {
            this.processingScopeField = processingScope.request;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute(processingScope.request)]
        public processingScope processingScope {
            get {
                return this.processingScopeField;
            }
            set {
                this.processingScopeField = value;
                this.RaisePropertyChanged("processingScope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public enum processingScope {
        
        /// <remarks/>
        not_applicable,
        
        /// <remarks/>
        request,
        
        /// <remarks/>
        business_entity,
        
        /// <remarks/>
        business_entity_component,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
    public partial class ReportProductionRequestTypeIWMStdReportProduction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productionOrderField;
        
        private double qtyDeliverField;
        
        private bool qtyDeliverFieldSpecified;
        
        private double qtyRejectField;
        
        private bool qtyRejectFieldSpecified;
        
        private string warehouseField;
        
        private string lotCodeField;
        
        private string postHoursField;
        
        private string reportMoreField;
        
        private string reportPreviousField;
        
        private string backFlushField;
        
        private string directReceiptField;
        
        private string completeField;
        
        private string serialNumberField;
        
        private string generateInboundField;
        
        private string releaseInboundField;
        
        private string runNumberField;
        
        private string locationField;
        
        private string insertNewSerialField;
        
        private string shiftField;
        
        private string receiptLocationField;
        
        private string completionDateField;
        
        private string kanbanIDField;
        
        private string rejectReasonField;
        
        private string transIDField;
        
        private string generateHUField;
        
        private string handlingUnitField;
        
        private string fromRepOperationField;
        
        private string crossdockEnabledField;
        
        private string loginCodeField;
        
        private string packageDefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ProductionOrder {
            get {
                return this.productionOrderField;
            }
            set {
                this.productionOrderField = value;
                this.RaisePropertyChanged("ProductionOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double QtyDeliver {
            get {
                return this.qtyDeliverField;
            }
            set {
                this.qtyDeliverField = value;
                this.RaisePropertyChanged("QtyDeliver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtyDeliverSpecified {
            get {
                return this.qtyDeliverFieldSpecified;
            }
            set {
                this.qtyDeliverFieldSpecified = value;
                this.RaisePropertyChanged("QtyDeliverSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double QtyReject {
            get {
                return this.qtyRejectField;
            }
            set {
                this.qtyRejectField = value;
                this.RaisePropertyChanged("QtyReject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QtyRejectSpecified {
            get {
                return this.qtyRejectFieldSpecified;
            }
            set {
                this.qtyRejectFieldSpecified = value;
                this.RaisePropertyChanged("QtyRejectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
                this.RaisePropertyChanged("Warehouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LotCode {
            get {
                return this.lotCodeField;
            }
            set {
                this.lotCodeField = value;
                this.RaisePropertyChanged("LotCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PostHours {
            get {
                return this.postHoursField;
            }
            set {
                this.postHoursField = value;
                this.RaisePropertyChanged("PostHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ReportMore {
            get {
                return this.reportMoreField;
            }
            set {
                this.reportMoreField = value;
                this.RaisePropertyChanged("ReportMore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ReportPrevious {
            get {
                return this.reportPreviousField;
            }
            set {
                this.reportPreviousField = value;
                this.RaisePropertyChanged("ReportPrevious");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BackFlush {
            get {
                return this.backFlushField;
            }
            set {
                this.backFlushField = value;
                this.RaisePropertyChanged("BackFlush");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string DirectReceipt {
            get {
                return this.directReceiptField;
            }
            set {
                this.directReceiptField = value;
                this.RaisePropertyChanged("DirectReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Complete {
            get {
                return this.completeField;
            }
            set {
                this.completeField = value;
                this.RaisePropertyChanged("Complete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string GenerateInbound {
            get {
                return this.generateInboundField;
            }
            set {
                this.generateInboundField = value;
                this.RaisePropertyChanged("GenerateInbound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ReleaseInbound {
            get {
                return this.releaseInboundField;
            }
            set {
                this.releaseInboundField = value;
                this.RaisePropertyChanged("ReleaseInbound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string RunNumber {
            get {
                return this.runNumberField;
            }
            set {
                this.runNumberField = value;
                this.RaisePropertyChanged("RunNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string InsertNewSerial {
            get {
                return this.insertNewSerialField;
            }
            set {
                this.insertNewSerialField = value;
                this.RaisePropertyChanged("InsertNewSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Shift {
            get {
                return this.shiftField;
            }
            set {
                this.shiftField = value;
                this.RaisePropertyChanged("Shift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ReceiptLocation {
            get {
                return this.receiptLocationField;
            }
            set {
                this.receiptLocationField = value;
                this.RaisePropertyChanged("ReceiptLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CompletionDate {
            get {
                return this.completionDateField;
            }
            set {
                this.completionDateField = value;
                this.RaisePropertyChanged("CompletionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string KanbanID {
            get {
                return this.kanbanIDField;
            }
            set {
                this.kanbanIDField = value;
                this.RaisePropertyChanged("KanbanID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string RejectReason {
            get {
                return this.rejectReasonField;
            }
            set {
                this.rejectReasonField = value;
                this.RaisePropertyChanged("RejectReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TransID {
            get {
                return this.transIDField;
            }
            set {
                this.transIDField = value;
                this.RaisePropertyChanged("TransID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string GenerateHU {
            get {
                return this.generateHUField;
            }
            set {
                this.generateHUField = value;
                this.RaisePropertyChanged("GenerateHU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string HandlingUnit {
            get {
                return this.handlingUnitField;
            }
            set {
                this.handlingUnitField = value;
                this.RaisePropertyChanged("HandlingUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string FromRepOperation {
            get {
                return this.fromRepOperationField;
            }
            set {
                this.fromRepOperationField = value;
                this.RaisePropertyChanged("FromRepOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string CrossdockEnabled {
            get {
                return this.crossdockEnabledField;
            }
            set {
                this.crossdockEnabledField = value;
                this.RaisePropertyChanged("CrossdockEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string LoginCode {
            get {
                return this.loginCodeField;
            }
            set {
                this.loginCodeField = value;
                this.RaisePropertyChanged("LoginCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string PackageDef {
            get {
                return this.packageDefField;
            }
            set {
                this.packageDefField = value;
                this.RaisePropertyChanged("PackageDef");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction", ConfigurationName="InforProducedQuantity.IWMStdReportProduction")]
    public interface IWMStdReportProduction {
        
        // CODEGEN: Generating message contract since message ReportProductionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(global::InforConnector.InforProducedQuantity.Message), Action="", Name="Result")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FilterType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActivationType))]
        global::InforConnector.InforProducedQuantity.ReportProductionResponse ReportProduction(global::InforConnector.InforProducedQuantity.ReportProductionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<global::InforConnector.InforProducedQuantity.ReportProductionResponse> ReportProductionAsync(global::InforConnector.InforProducedQuantity.ReportProductionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportProduction", WrapperNamespace="http://www.infor.com/businessinterface/IWMStdReportProduction", IsWrapped=true)]
    public partial class ReportProductionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
        public global::InforConnector.InforProducedQuantity.ActivationType Activation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportProductionRequest", Namespace="", Order=0)]
        public global::InforConnector.InforProducedQuantity.ReportProductionRequestType ReportProductionRequest1;
        
        public ReportProductionRequest() {
        }
        
        public ReportProductionRequest(global::InforConnector.InforProducedQuantity.ActivationType Activation, global::InforConnector.InforProducedQuantity.ReportProductionRequestType ReportProductionRequest1) {
            this.Activation = Activation;
            this.ReportProductionRequest1 = ReportProductionRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReportProductionResponse", WrapperNamespace="http://www.infor.com/businessinterface/IWMStdReportProduction", IsWrapped=true)]
    public partial class ReportProductionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportProductionResponse", Namespace="", Order=0)]
        public global::InforConnector.InforProducedQuantity.ReportProductionResponseType ReportProductionResponse1;
        
        public ReportProductionResponse() {
        }
        
        public ReportProductionResponse(global::InforConnector.InforProducedQuantity.ReportProductionResponseType ReportProductionResponse1) {
            this.ReportProductionResponse1 = ReportProductionResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWMStdReportProductionChannel : global::InforConnector.InforProducedQuantity.IWMStdReportProduction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMStdReportProductionClient : System.ServiceModel.ClientBase<global::InforConnector.InforProducedQuantity.IWMStdReportProduction>, global::InforConnector.InforProducedQuantity.IWMStdReportProduction {
        
        public WMStdReportProductionClient() {
        }
        
        public WMStdReportProductionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMStdReportProductionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMStdReportProductionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMStdReportProductionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::InforConnector.InforProducedQuantity.ReportProductionResponse global::InforConnector.InforProducedQuantity.IWMStdReportProduction.ReportProduction(global::InforConnector.InforProducedQuantity.ReportProductionRequest request) {
            return base.Channel.ReportProduction(request);
        }
        
        public global::InforConnector.InforProducedQuantity.ReportProductionResponseType ReportProduction(global::InforConnector.InforProducedQuantity.ActivationType Activation, global::InforConnector.InforProducedQuantity.ReportProductionRequestType ReportProductionRequest1) {
            global::InforConnector.InforProducedQuantity.ReportProductionRequest inValue = new global::InforConnector.InforProducedQuantity.ReportProductionRequest();
            inValue.Activation = Activation;
            inValue.ReportProductionRequest1 = ReportProductionRequest1;
            global::InforConnector.InforProducedQuantity.ReportProductionResponse retVal = ((global::InforConnector.InforProducedQuantity.IWMStdReportProduction)(this)).ReportProduction(inValue);
            return retVal.ReportProductionResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::InforConnector.InforProducedQuantity.ReportProductionResponse> global::InforConnector.InforProducedQuantity.IWMStdReportProduction.ReportProductionAsync(global::InforConnector.InforProducedQuantity.ReportProductionRequest request) {
            return base.Channel.ReportProductionAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::InforConnector.InforProducedQuantity.ReportProductionResponse> ReportProductionAsync(global::InforConnector.InforProducedQuantity.ActivationType Activation, global::InforConnector.InforProducedQuantity.ReportProductionRequestType ReportProductionRequest1) {
            global::InforConnector.InforProducedQuantity.ReportProductionRequest inValue = new global::InforConnector.InforProducedQuantity.ReportProductionRequest();
            inValue.Activation = Activation;
            inValue.ReportProductionRequest1 = ReportProductionRequest1;
            return ((global::InforConnector.InforProducedQuantity.IWMStdReportProduction)(this)).ReportProductionAsync(inValue);
        }
    }
}
