//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using UADMSoapWrapper;

// 
// This source code was auto-generated by wsdl, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.Web.Services.WebServiceAttribute(Namespace = Constants.NameSpace)]
[System.Web.Services.WebServiceBindingAttribute(Name = "IOP_EXTServiceSoapBinding", Namespace = Constants.NameSpace)]
[SoapDocumentService(RoutingStyle = SoapServiceRoutingStyle.RequestElement)]
public abstract partial class IOP_EXTService : System.Web.Services.WebService
{
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = Constants.NameSpace, ResponseNamespace = Constants.NameSpace, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("ERPOrderResponse")]

    public abstract ERPOrderResponse ImportERPOrder(ERPOrderRequest ERPOrderInfo);

    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = Constants.NameSpace, ResponseNamespace = Constants.NameSpace, Use = System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("MaterialDefinitionResponse")]
    public abstract MaterialDefinitionResponse ImportMaterialDefinition(MaterialDefinitionRequest MaterialDefinition);
}



[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = Constants.NameSpace)]
public class MaterialDefinitionRequest
{
    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialRevision { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialFamily { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UoM { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(bool), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Serialized { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(bool), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Customized { get; set; } // se false aggiungo 9 spazi bianchi al material code
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = Constants.NameSpace)]
public class MaterialDefinitionResponse
{
    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialRevision { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public class ToBeConsumedMaterial
{
    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaterialRevision { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(decimal), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Quantity { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UoM { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Sequence { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
public class Order
{
    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name { get; set; }
    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Sequence { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkArea { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int NextOrder { get; set; }

    //[System.Xml.Serialization.XmlElementAttribute(typeof(List<ToBeConsumedMaterial>), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlElementAttribute(typeof(List<Operation>), Namespace = "", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlArrayItemAttribute("IOP_EXTService", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ToBeConsumedMaterial", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]

    public ToBeConsumedMaterial[] ToBeConsumedMaterials { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = Constants.NameSpace)]
public class ERPOrderRequest
{
    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ERPId { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FinalMaterialCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FinalMaterialRevision { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Quantity { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(DateTime), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DateTime EstimatedStartTime { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(DateTime), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DateTime EstimatedEndTime { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Priority { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(long), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long CycleTimeMs { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(long), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long SetupTimeMs { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Operators { get; set; }

    //[System.Xml.Serialization.XmlElementAttribute(typeof(List<Operation>), Namespace = "", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //[System.Xml.Serialization.XmlArrayItemAttribute("IOP_EXTService", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Order", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]

    public Order[] Orders { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = Constants.NameSpace)]
public class ERPOrderResponse
{
    [System.Xml.Serialization.XmlElementAttribute(typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int WorkOrderId { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkOrderNId { get; set; }
}
