//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="IWMStdReportProductionSoapBinding", Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Message))]
public interface IIWMStdReportProductionSoapBinding {
   
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.infor.com/businessinterface/IWMStdReportProduction", ResponseNamespace="http://www.infor.com/businessinterface/IWMStdReportProduction", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("ReportProductionResponse")]
    ReportProductionResponseType ReportProduction(ReportProductionRequestType ReportProductionRequest);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
[System.Xml.Serialization.XmlRootAttribute("Activation", Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction", IsNullable=false)]
public partial class ActivationType : System.Web.Services.Protocols.SoapHeader {
    
    private string usernameField;
    
    private string passwordField;
    
    private int companyField;
    
    private bool companyFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool companySpecified {
        get {
            return this.companyFieldSpecified;
        }
        set {
            this.companyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class EmptyValueType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class ComparisonExpressionType {
    
    private ComparisonExpressionTypeComparisonOperator comparisonOperatorField;
    
    private object itemField;
    
    private object item1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public ComparisonExpressionTypeComparisonOperator comparisonOperator {
        get {
            return this.comparisonOperatorField;
        }
        set {
            this.comparisonOperatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributeName", typeof(filterAttributeListDT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("emptyValue", typeof(EmptyValueType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("instanceValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attributeName", typeof(filterAttributeListDT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("emptyValue", typeof(EmptyValueType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("instanceValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public object Item1 {
        get {
            return this.item1Field;
        }
        set {
            this.item1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public enum ComparisonExpressionTypeComparisonOperator {
    
    /// <remarks/>
    le,
    
    /// <remarks/>
    lt,
    
    /// <remarks/>
    ge,
    
    /// <remarks/>
    gt,
    
    /// <remarks/>
    ne,
    
    /// <remarks/>
    eq,
    
    /// <remarks/>
    like,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public enum filterAttributeListDT {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ProductionOrder")]
    IWMStdReportProductionProductionOrder,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.QtyDeliver")]
    IWMStdReportProductionQtyDeliver,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.QtyReject")]
    IWMStdReportProductionQtyReject,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Warehouse")]
    IWMStdReportProductionWarehouse,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.LotCode")]
    IWMStdReportProductionLotCode,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.PostHours")]
    IWMStdReportProductionPostHours,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReportMore")]
    IWMStdReportProductionReportMore,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReportPrevious")]
    IWMStdReportProductionReportPrevious,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.BackFlush")]
    IWMStdReportProductionBackFlush,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.DirectReceipt")]
    IWMStdReportProductionDirectReceipt,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Complete")]
    IWMStdReportProductionComplete,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.SerialNumber")]
    IWMStdReportProductionSerialNumber,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.GenerateInbound")]
    IWMStdReportProductionGenerateInbound,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReleaseInbound")]
    IWMStdReportProductionReleaseInbound,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.RunNumber")]
    IWMStdReportProductionRunNumber,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Location")]
    IWMStdReportProductionLocation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.InsertNewSerial")]
    IWMStdReportProductionInsertNewSerial,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.Shift")]
    IWMStdReportProductionShift,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.ReceiptLocation")]
    IWMStdReportProductionReceiptLocation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.CompletionDate")]
    IWMStdReportProductionCompletionDate,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.KanbanID")]
    IWMStdReportProductionKanbanID,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.RejectReason")]
    IWMStdReportProductionRejectReason,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.TransID")]
    IWMStdReportProductionTransID,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.GenerateHU")]
    IWMStdReportProductionGenerateHU,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.HandlingUnit")]
    IWMStdReportProductionHandlingUnit,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.FromRepOperation")]
    IWMStdReportProductionFromRepOperation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.CrossdockEnabled")]
    IWMStdReportProductionCrossdockEnabled,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.LoginCode")]
    IWMStdReportProductionLoginCode,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.OutData")]
    IWMStdReportProductionOutData,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("IWMStdReportProduction.PackageDef")]
    IWMStdReportProductionPackageDef,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class LogicalExpressionType {
    
    private LogicalExpressionTypeLogicalOperator logicalOperatorField;
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LogicalExpressionTypeLogicalOperator logicalOperator {
        get {
            return this.logicalOperatorField;
        }
        set {
            this.logicalOperatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ComparisonExpression", typeof(ComparisonExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("LogicalExpression", typeof(LogicalExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public enum LogicalExpressionTypeLogicalOperator {
    
    /// <remarks/>
    or,
    
    /// <remarks/>
    and,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class FilterType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ComparisonExpression", typeof(ComparisonExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("LogicalExpression", typeof(LogicalExpressionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InformationMessage))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DetailMessage))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class Message {
    
    private string messageIndexField;
    
    private string messageCodeField;
    
    private MessageMessageType messageTypeField;
    
    private string messageTextField;
    
    private string messageSourceField;
    
    private DetailMessage[] messageDetailsField;
    
    private string messageCorrectiveActionField;
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private MessageMessageReference messageReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string messageIndex {
        get {
            return this.messageIndexField;
        }
        set {
            this.messageIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string messageCode {
        get {
            return this.messageCodeField;
        }
        set {
            this.messageCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MessageMessageType messageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string messageText {
        get {
            return this.messageTextField;
        }
        set {
            this.messageTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string messageSource {
        get {
            return this.messageSourceField;
        }
        set {
            this.messageSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DetailMessage[] MessageDetails {
        get {
            return this.messageDetailsField;
        }
        set {
            this.messageDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string messageCorrectiveAction {
        get {
            return this.messageCorrectiveActionField;
        }
        set {
            this.messageCorrectiveActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("messageAdditionalHelpText", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("messageAdditionalHelpURI", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MessageMessageReference MessageReference {
        get {
            return this.messageReferenceField;
        }
        set {
            this.messageReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public enum MessageMessageType {
    
    /// <remarks/>
    Error,
    
    /// <remarks/>
    Warning,
    
    /// <remarks/>
    Information,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class DetailMessage : Message {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(":messageAdditionalHelpText")]
    messageAdditionalHelpText,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(":messageAdditionalHelpURI")]
    messageAdditionalHelpURI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class MessageMessageReference {
    
    private string messageReferenceTypeField;
    
    private object messageReferenceInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string messageReferenceType {
        get {
            return this.messageReferenceTypeField;
        }
        set {
            this.messageReferenceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object messageReferenceInfo {
        get {
            return this.messageReferenceInfoField;
        }
        set {
            this.messageReferenceInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class InformationMessage : Message {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class ReportProductionResponseType {
    
    private ReportProductionResponseTypeIWMStdReportProduction[] dataAreaField;
    
    private InformationMessage[] informationAreaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("IWMStdReportProduction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ReportProductionResponseTypeIWMStdReportProduction[] DataArea {
        get {
            return this.dataAreaField;
        }
        set {
            this.dataAreaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public InformationMessage[] InformationArea {
        get {
            return this.informationAreaField;
        }
        set {
            this.informationAreaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class ReportProductionResponseTypeIWMStdReportProduction {
    
    private string outDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OutData {
        get {
            return this.outDataField;
        }
        set {
            this.outDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class ReportProductionRequestType {
    
    private ReportProductionRequestTypeControlArea controlAreaField;
    
    private ReportProductionRequestTypeIWMStdReportProduction[] dataAreaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReportProductionRequestTypeControlArea ControlArea {
        get {
            return this.controlAreaField;
        }
        set {
            this.controlAreaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("IWMStdReportProduction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ReportProductionRequestTypeIWMStdReportProduction[] DataArea {
        get {
            return this.dataAreaField;
        }
        set {
            this.dataAreaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class ReportProductionRequestTypeControlArea {
    
    private processingScope processingScopeField;
    
    public ReportProductionRequestTypeControlArea() {
        this.processingScopeField = processingScope.request;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(processingScope.request)]
    public processingScope processingScope {
        get {
            return this.processingScopeField;
        }
        set {
            this.processingScopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public enum processingScope {
    
    /// <remarks/>
    not_applicable,
    
    /// <remarks/>
    request,
    
    /// <remarks/>
    business_entity,
    
    /// <remarks/>
    business_entity_component,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.infor.com/businessinterface/IWMStdReportProduction")]
public partial class ReportProductionRequestTypeIWMStdReportProduction {
    
    private string productionOrderField;
    
    private double qtyDeliverField;
    
    private bool qtyDeliverFieldSpecified;
    
    private double qtyRejectField;
    
    private bool qtyRejectFieldSpecified;
    
    private string warehouseField;
    
    private string lotCodeField;
    
    private string postHoursField;
    
    private string reportMoreField;
    
    private string reportPreviousField;
    
    private string backFlushField;
    
    private string directReceiptField;
    
    private string completeField;
    
    private string serialNumberField;
    
    private string generateInboundField;
    
    private string releaseInboundField;
    
    private string runNumberField;
    
    private string locationField;
    
    private string insertNewSerialField;
    
    private string shiftField;
    
    private string receiptLocationField;
    
    private string completionDateField;
    
    private string kanbanIDField;
    
    private string rejectReasonField;
    
    private string transIDField;
    
    private string generateHUField;
    
    private string handlingUnitField;
    
    private string fromRepOperationField;
    
    private string crossdockEnabledField;
    
    private string loginCodeField;
    
    private string packageDefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductionOrder {
        get {
            return this.productionOrderField;
        }
        set {
            this.productionOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double QtyDeliver {
        get {
            return this.qtyDeliverField;
        }
        set {
            this.qtyDeliverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QtyDeliverSpecified {
        get {
            return this.qtyDeliverFieldSpecified;
        }
        set {
            this.qtyDeliverFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double QtyReject {
        get {
            return this.qtyRejectField;
        }
        set {
            this.qtyRejectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QtyRejectSpecified {
        get {
            return this.qtyRejectFieldSpecified;
        }
        set {
            this.qtyRejectFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Warehouse {
        get {
            return this.warehouseField;
        }
        set {
            this.warehouseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LotCode {
        get {
            return this.lotCodeField;
        }
        set {
            this.lotCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostHours {
        get {
            return this.postHoursField;
        }
        set {
            this.postHoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReportMore {
        get {
            return this.reportMoreField;
        }
        set {
            this.reportMoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReportPrevious {
        get {
            return this.reportPreviousField;
        }
        set {
            this.reportPreviousField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BackFlush {
        get {
            return this.backFlushField;
        }
        set {
            this.backFlushField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DirectReceipt {
        get {
            return this.directReceiptField;
        }
        set {
            this.directReceiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Complete {
        get {
            return this.completeField;
        }
        set {
            this.completeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GenerateInbound {
        get {
            return this.generateInboundField;
        }
        set {
            this.generateInboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReleaseInbound {
        get {
            return this.releaseInboundField;
        }
        set {
            this.releaseInboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RunNumber {
        get {
            return this.runNumberField;
        }
        set {
            this.runNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InsertNewSerial {
        get {
            return this.insertNewSerialField;
        }
        set {
            this.insertNewSerialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Shift {
        get {
            return this.shiftField;
        }
        set {
            this.shiftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReceiptLocation {
        get {
            return this.receiptLocationField;
        }
        set {
            this.receiptLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompletionDate {
        get {
            return this.completionDateField;
        }
        set {
            this.completionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KanbanID {
        get {
            return this.kanbanIDField;
        }
        set {
            this.kanbanIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RejectReason {
        get {
            return this.rejectReasonField;
        }
        set {
            this.rejectReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransID {
        get {
            return this.transIDField;
        }
        set {
            this.transIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GenerateHU {
        get {
            return this.generateHUField;
        }
        set {
            this.generateHUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HandlingUnit {
        get {
            return this.handlingUnitField;
        }
        set {
            this.handlingUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FromRepOperation {
        get {
            return this.fromRepOperationField;
        }
        set {
            this.fromRepOperationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CrossdockEnabled {
        get {
            return this.crossdockEnabledField;
        }
        set {
            this.crossdockEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoginCode {
        get {
            return this.loginCodeField;
        }
        set {
            this.loginCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PackageDef {
        get {
            return this.packageDefField;
        }
        set {
            this.packageDefField = value;
        }
    }
}
