//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWatchConnectorLibrary.OTService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.SendMaterialCallRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.GetSerialsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.GetMaterialCallsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.AcceptMaterialCallRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.StartSerialRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.LoginRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendTeamLeaderCallRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.SendMaterialCallRequest))]
    public partial class SendTeamLeaderCallRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMaterialCallRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SendMaterialCallRequest : SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSerialsRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetSerialsRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMaterialCallsRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetMaterialCallsRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAreaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkArea {
            get {
                return this.WorkAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAreaField, value) != true)) {
                    this.WorkAreaField = value;
                    this.RaisePropertyChanged("WorkArea");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTeamLeaderCallsRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetTeamLeaderCallsRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAreaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkArea {
            get {
                return this.WorkAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAreaField, value) != true)) {
                    this.WorkAreaField = value;
                    this.RaisePropertyChanged("WorkArea");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptMaterialCallRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class AcceptMaterialCallRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallId {
            get {
                return this.CallIdField;
            }
            set {
                if ((this.CallIdField.Equals(value) != true)) {
                    this.CallIdField = value;
                    this.RaisePropertyChanged("CallId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptTeamLeaderCallRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class AcceptTeamLeaderCallRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallId {
            get {
                return this.CallIdField;
            }
            set {
                if ((this.CallIdField.Equals(value) != true)) {
                    this.CallIdField = value;
                    this.RaisePropertyChanged("CallId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartSerialRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class StartSerialRequest : SmartWatchConnectorLibrary.OTService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : SmartWatchConnectorLibrary.OTService.Request {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.SendMaterialCallResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.GetSerialsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.GetMaterialCallsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.AcceptMaterialCallResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.StartSerialResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.LoginResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucceededField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succeeded {
            get {
                return this.SucceededField;
            }
            set {
                if ((this.SucceededField.Equals(value) != true)) {
                    this.SucceededField = value;
                    this.RaisePropertyChanged("Succeeded");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendTeamLeaderCallResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SendTeamLeaderCallResponse : SmartWatchConnectorLibrary.OTService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMaterialCallResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SendMaterialCallResponse : SmartWatchConnectorLibrary.OTService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSerialsResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetSerialsResponse : SmartWatchConnectorLibrary.OTService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmartWatchConnectorLibrary.OTService.SerialItem[] SerialsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmartWatchConnectorLibrary.OTService.SerialItem[] Serials {
            get {
                return this.SerialsField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialsField, value) != true)) {
                    this.SerialsField = value;
                    this.RaisePropertyChanged("Serials");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMaterialCallsResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetMaterialCallsResponse : SmartWatchConnectorLibrary.OTService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmartWatchConnectorLibrary.OTService.MaterialCall[] MaterialCallsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmartWatchConnectorLibrary.OTService.MaterialCall[] MaterialCalls {
            get {
                return this.MaterialCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialCallsField, value) != true)) {
                    this.MaterialCallsField = value;
                    this.RaisePropertyChanged("MaterialCalls");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTeamLeaderCallsResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetTeamLeaderCallsResponse : SmartWatchConnectorLibrary.OTService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmartWatchConnectorLibrary.OTService.Call[] TeamLeaderCallsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmartWatchConnectorLibrary.OTService.Call[] TeamLeaderCalls {
            get {
                return this.TeamLeaderCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamLeaderCallsField, value) != true)) {
                    this.TeamLeaderCallsField = value;
                    this.RaisePropertyChanged("TeamLeaderCalls");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptMaterialCallResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class AcceptMaterialCallResponse : SmartWatchConnectorLibrary.OTService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptTeamLeaderCallResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class AcceptTeamLeaderCallResponse : SmartWatchConnectorLibrary.OTService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartSerialResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class StartSerialResponse : SmartWatchConnectorLibrary.OTService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : SmartWatchConnectorLibrary.OTService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAreaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkArea {
            get {
                return this.WorkAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAreaField, value) != true)) {
                    this.WorkAreaField = value;
                    this.RaisePropertyChanged("WorkArea");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialItem", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SerialItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterialCall", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    public partial class MaterialCall : SmartWatchConnectorLibrary.OTService.Call {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Call", Namespace="http://schemas.datacontract.org/2004/07/OTWeb.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SmartWatchConnectorLibrary.OTService.MaterialCall))]
    public partial class Call : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CallDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAreaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CallDate {
            get {
                return this.CallDateField;
            }
            set {
                if ((this.CallDateField.Equals(value) != true)) {
                    this.CallDateField = value;
                    this.RaisePropertyChanged("CallDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CallId {
            get {
                return this.CallIdField;
            }
            set {
                if ((this.CallIdField.Equals(value) != true)) {
                    this.CallIdField = value;
                    this.RaisePropertyChanged("CallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkArea {
            get {
                return this.WorkAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAreaField, value) != true)) {
                    this.WorkAreaField = value;
                    this.RaisePropertyChanged("WorkArea");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OTService.IOTService")]
    public interface IOTService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/Login", ReplyAction="http://tempuri.org/IOTService/LoginResponse")]
        SmartWatchConnectorLibrary.OTService.LoginResponse Login(SmartWatchConnectorLibrary.OTService.LoginRequest loginRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/Login", ReplyAction="http://tempuri.org/IOTService/LoginResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.LoginResponse> LoginAsync(SmartWatchConnectorLibrary.OTService.LoginRequest loginRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/SendTeamLeaderCall", ReplyAction="http://tempuri.org/IOTService/SendTeamLeaderCallResponse")]
        SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallResponse SendTeamLeaderCall(SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallRequest teamLeaderCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/SendTeamLeaderCall", ReplyAction="http://tempuri.org/IOTService/SendTeamLeaderCallResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallResponse> SendTeamLeaderCallAsync(SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallRequest teamLeaderCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/SendMaterialCall", ReplyAction="http://tempuri.org/IOTService/SendMaterialCallResponse")]
        SmartWatchConnectorLibrary.OTService.SendMaterialCallResponse SendMaterialCall(SmartWatchConnectorLibrary.OTService.SendMaterialCallRequest materialCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/SendMaterialCall", ReplyAction="http://tempuri.org/IOTService/SendMaterialCallResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.SendMaterialCallResponse> SendMaterialCallAsync(SmartWatchConnectorLibrary.OTService.SendMaterialCallRequest materialCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/GetSerials", ReplyAction="http://tempuri.org/IOTService/GetSerialsResponse")]
        SmartWatchConnectorLibrary.OTService.GetSerialsResponse GetSerials([System.ServiceModel.MessageParameterAttribute(Name="getSerials")] SmartWatchConnectorLibrary.OTService.GetSerialsRequest getSerials1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/GetSerials", ReplyAction="http://tempuri.org/IOTService/GetSerialsResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.GetSerialsResponse> GetSerialsAsync(SmartWatchConnectorLibrary.OTService.GetSerialsRequest getSerials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/GetMaterialCalls", ReplyAction="http://tempuri.org/IOTService/GetMaterialCallsResponse")]
        SmartWatchConnectorLibrary.OTService.GetMaterialCallsResponse GetMaterialCalls([System.ServiceModel.MessageParameterAttribute(Name="getMaterialCalls")] SmartWatchConnectorLibrary.OTService.GetMaterialCallsRequest getMaterialCalls1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/GetMaterialCalls", ReplyAction="http://tempuri.org/IOTService/GetMaterialCallsResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.GetMaterialCallsResponse> GetMaterialCallsAsync(SmartWatchConnectorLibrary.OTService.GetMaterialCallsRequest getMaterialCalls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/GetTeamLeaderCalls", ReplyAction="http://tempuri.org/IOTService/GetTeamLeaderCallsResponse")]
        SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsResponse GetTeamLeaderCalls([System.ServiceModel.MessageParameterAttribute(Name="getTeamLeaderCalls")] SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsRequest getTeamLeaderCalls1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/GetTeamLeaderCalls", ReplyAction="http://tempuri.org/IOTService/GetTeamLeaderCallsResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsResponse> GetTeamLeaderCallsAsync(SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsRequest getTeamLeaderCalls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/AcceptMaterialCall", ReplyAction="http://tempuri.org/IOTService/AcceptMaterialCallResponse")]
        SmartWatchConnectorLibrary.OTService.AcceptMaterialCallResponse AcceptMaterialCall([System.ServiceModel.MessageParameterAttribute(Name="acceptMaterialCall")] SmartWatchConnectorLibrary.OTService.AcceptMaterialCallRequest acceptMaterialCall1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/AcceptMaterialCall", ReplyAction="http://tempuri.org/IOTService/AcceptMaterialCallResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.AcceptMaterialCallResponse> AcceptMaterialCallAsync(SmartWatchConnectorLibrary.OTService.AcceptMaterialCallRequest acceptMaterialCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/AcceptTeamLeaderCall", ReplyAction="http://tempuri.org/IOTService/AcceptTeamLeaderCallResponse")]
        SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallResponse AcceptTeamLeaderCall([System.ServiceModel.MessageParameterAttribute(Name="acceptTeamLeaderCall")] SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallRequest acceptTeamLeaderCall1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/AcceptTeamLeaderCall", ReplyAction="http://tempuri.org/IOTService/AcceptTeamLeaderCallResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallResponse> AcceptTeamLeaderCallAsync(SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallRequest acceptTeamLeaderCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/StartSerial", ReplyAction="http://tempuri.org/IOTService/StartSerialResponse")]
        SmartWatchConnectorLibrary.OTService.StartSerialResponse StartSerial(SmartWatchConnectorLibrary.OTService.StartSerialRequest acceptTeamLeaderCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTService/StartSerial", ReplyAction="http://tempuri.org/IOTService/StartSerialResponse")]
        System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.StartSerialResponse> StartSerialAsync(SmartWatchConnectorLibrary.OTService.StartSerialRequest acceptTeamLeaderCall);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOTServiceChannel : SmartWatchConnectorLibrary.OTService.IOTService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OTServiceClient : System.ServiceModel.ClientBase<SmartWatchConnectorLibrary.OTService.IOTService>, SmartWatchConnectorLibrary.OTService.IOTService {
        
        public OTServiceClient() {
        }
        
        public OTServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OTServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmartWatchConnectorLibrary.OTService.LoginResponse Login(SmartWatchConnectorLibrary.OTService.LoginRequest loginRequest) {
            return base.Channel.Login(loginRequest);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.LoginResponse> LoginAsync(SmartWatchConnectorLibrary.OTService.LoginRequest loginRequest) {
            return base.Channel.LoginAsync(loginRequest);
        }
        
        public SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallResponse SendTeamLeaderCall(SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallRequest teamLeaderCall) {
            return base.Channel.SendTeamLeaderCall(teamLeaderCall);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallResponse> SendTeamLeaderCallAsync(SmartWatchConnectorLibrary.OTService.SendTeamLeaderCallRequest teamLeaderCall) {
            return base.Channel.SendTeamLeaderCallAsync(teamLeaderCall);
        }
        
        public SmartWatchConnectorLibrary.OTService.SendMaterialCallResponse SendMaterialCall(SmartWatchConnectorLibrary.OTService.SendMaterialCallRequest materialCall) {
            return base.Channel.SendMaterialCall(materialCall);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.SendMaterialCallResponse> SendMaterialCallAsync(SmartWatchConnectorLibrary.OTService.SendMaterialCallRequest materialCall) {
            return base.Channel.SendMaterialCallAsync(materialCall);
        }
        
        public SmartWatchConnectorLibrary.OTService.GetSerialsResponse GetSerials(SmartWatchConnectorLibrary.OTService.GetSerialsRequest getSerials1) {
            return base.Channel.GetSerials(getSerials1);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.GetSerialsResponse> GetSerialsAsync(SmartWatchConnectorLibrary.OTService.GetSerialsRequest getSerials) {
            return base.Channel.GetSerialsAsync(getSerials);
        }
        
        public SmartWatchConnectorLibrary.OTService.GetMaterialCallsResponse GetMaterialCalls(SmartWatchConnectorLibrary.OTService.GetMaterialCallsRequest getMaterialCalls1) {
            return base.Channel.GetMaterialCalls(getMaterialCalls1);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.GetMaterialCallsResponse> GetMaterialCallsAsync(SmartWatchConnectorLibrary.OTService.GetMaterialCallsRequest getMaterialCalls) {
            return base.Channel.GetMaterialCallsAsync(getMaterialCalls);
        }
        
        public SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsResponse GetTeamLeaderCalls(SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsRequest getTeamLeaderCalls1) {
            return base.Channel.GetTeamLeaderCalls(getTeamLeaderCalls1);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsResponse> GetTeamLeaderCallsAsync(SmartWatchConnectorLibrary.OTService.GetTeamLeaderCallsRequest getTeamLeaderCalls) {
            return base.Channel.GetTeamLeaderCallsAsync(getTeamLeaderCalls);
        }
        
        public SmartWatchConnectorLibrary.OTService.AcceptMaterialCallResponse AcceptMaterialCall(SmartWatchConnectorLibrary.OTService.AcceptMaterialCallRequest acceptMaterialCall1) {
            return base.Channel.AcceptMaterialCall(acceptMaterialCall1);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.AcceptMaterialCallResponse> AcceptMaterialCallAsync(SmartWatchConnectorLibrary.OTService.AcceptMaterialCallRequest acceptMaterialCall) {
            return base.Channel.AcceptMaterialCallAsync(acceptMaterialCall);
        }
        
        public SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallResponse AcceptTeamLeaderCall(SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallRequest acceptTeamLeaderCall1) {
            return base.Channel.AcceptTeamLeaderCall(acceptTeamLeaderCall1);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallResponse> AcceptTeamLeaderCallAsync(SmartWatchConnectorLibrary.OTService.AcceptTeamLeaderCallRequest acceptTeamLeaderCall) {
            return base.Channel.AcceptTeamLeaderCallAsync(acceptTeamLeaderCall);
        }
        
        public SmartWatchConnectorLibrary.OTService.StartSerialResponse StartSerial(SmartWatchConnectorLibrary.OTService.StartSerialRequest acceptTeamLeaderCall) {
            return base.Channel.StartSerial(acceptTeamLeaderCall);
        }
        
        public System.Threading.Tasks.Task<SmartWatchConnectorLibrary.OTService.StartSerialResponse> StartSerialAsync(SmartWatchConnectorLibrary.OTService.StartSerialRequest acceptTeamLeaderCall) {
            return base.Channel.StartSerialAsync(acceptTeamLeaderCall);
        }
    }
}
