//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTestConsole.OPEXTSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/UADMSoapWrapp.DataTypes.OPEXT")]
    [System.SerializableAttribute()]
    public partial class WorkOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ERPIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EstimatedEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EstimatedStartTimeField;
        
        private string FinalMaterialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalMaterialRevisionField;
        
        private int PriorityField;
        
        private int QuantityField;
        
        private ServiceTestConsole.OPEXTSoapService.ToBeConsumedMaterial[] ToBeConsumedMaterialsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ERPId {
            get {
                return this.ERPIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ERPIdField, value) != true)) {
                    this.ERPIdField = value;
                    this.RaisePropertyChanged("ERPId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EstimatedEndTime {
            get {
                return this.EstimatedEndTimeField;
            }
            set {
                if ((this.EstimatedEndTimeField.Equals(value) != true)) {
                    this.EstimatedEndTimeField = value;
                    this.RaisePropertyChanged("EstimatedEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EstimatedStartTime {
            get {
                return this.EstimatedStartTimeField;
            }
            set {
                if ((this.EstimatedStartTimeField.Equals(value) != true)) {
                    this.EstimatedStartTimeField = value;
                    this.RaisePropertyChanged("EstimatedStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FinalMaterialCode {
            get {
                return this.FinalMaterialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalMaterialCodeField, value) != true)) {
                    this.FinalMaterialCodeField = value;
                    this.RaisePropertyChanged("FinalMaterialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalMaterialRevision {
            get {
                return this.FinalMaterialRevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalMaterialRevisionField, value) != true)) {
                    this.FinalMaterialRevisionField = value;
                    this.RaisePropertyChanged("FinalMaterialRevision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceTestConsole.OPEXTSoapService.ToBeConsumedMaterial[] ToBeConsumedMaterials {
            get {
                return this.ToBeConsumedMaterialsField;
            }
            set {
                if ((object.ReferenceEquals(this.ToBeConsumedMaterialsField, value) != true)) {
                    this.ToBeConsumedMaterialsField = value;
                    this.RaisePropertyChanged("ToBeConsumedMaterials");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToBeConsumedMaterial", Namespace="http://schemas.datacontract.org/2004/07/UADMSoapWrapp.DataTypes.OPEXT")]
    [System.SerializableAttribute()]
    public partial class ToBeConsumedMaterial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MaterialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialRevisionField;
        
        private decimal QuantityField;
        
        private int SequenceField;
        
        private string UoMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MaterialCode {
            get {
                return this.MaterialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialCodeField, value) != true)) {
                    this.MaterialCodeField = value;
                    this.RaisePropertyChanged("MaterialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialRevision {
            get {
                return this.MaterialRevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialRevisionField, value) != true)) {
                    this.MaterialRevisionField = value;
                    this.RaisePropertyChanged("MaterialRevision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UoM {
            get {
                return this.UoMField;
            }
            set {
                if ((object.ReferenceEquals(this.UoMField, value) != true)) {
                    this.UoMField = value;
                    this.RaisePropertyChanged("UoM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/UADMSoapWrapp.DataTypes.OPEXT")]
    [System.SerializableAttribute()]
    public partial class WorkOrderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int WorkOrderIdField;
        
        private string WorkOrderNIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int WorkOrderId {
            get {
                return this.WorkOrderIdField;
            }
            set {
                if ((this.WorkOrderIdField.Equals(value) != true)) {
                    this.WorkOrderIdField = value;
                    this.RaisePropertyChanged("WorkOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string WorkOrderNId {
            get {
                return this.WorkOrderNIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderNIdField, value) != true)) {
                    this.WorkOrderNIdField = value;
                    this.RaisePropertyChanged("WorkOrderNId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterialDefinitionRequest", Namespace="http://schemas.datacontract.org/2004/07/UADMSoapWrapp.DataTypes.OPEXT")]
    [System.SerializableAttribute()]
    public partial class MaterialDefinitionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private string MaterialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialRevisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SerializedField;
        
        private string UoMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MaterialCode {
            get {
                return this.MaterialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialCodeField, value) != true)) {
                    this.MaterialCodeField = value;
                    this.RaisePropertyChanged("MaterialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialRevision {
            get {
                return this.MaterialRevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialRevisionField, value) != true)) {
                    this.MaterialRevisionField = value;
                    this.RaisePropertyChanged("MaterialRevision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Serialized {
            get {
                return this.SerializedField;
            }
            set {
                if ((this.SerializedField.Equals(value) != true)) {
                    this.SerializedField = value;
                    this.RaisePropertyChanged("Serialized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UoM {
            get {
                return this.UoMField;
            }
            set {
                if ((object.ReferenceEquals(this.UoMField, value) != true)) {
                    this.UoMField = value;
                    this.RaisePropertyChanged("UoM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterialDefinitionResponse", Namespace="http://schemas.datacontract.org/2004/07/UADMSoapWrapp.DataTypes.OPEXT")]
    [System.SerializableAttribute()]
    public partial class MaterialDefinitionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MaterialCodeField;
        
        private string MaterialRevisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MaterialCode {
            get {
                return this.MaterialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialCodeField, value) != true)) {
                    this.MaterialCodeField = value;
                    this.RaisePropertyChanged("MaterialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MaterialRevision {
            get {
                return this.MaterialRevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialRevisionField, value) != true)) {
                    this.MaterialRevisionField = value;
                    this.RaisePropertyChanged("MaterialRevision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Engineering.DAB.UADMSoapWrap", ConfigurationName="OPEXTSoapService.IOPEXTWrapper")]
    public interface IOPEXTWrapper {
        
        [System.ServiceModel.OperationContractAttribute(Action="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportWorkOrder", ReplyAction="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportWorkOrderResponse")]
        ServiceTestConsole.OPEXTSoapService.WorkOrderResponse ImportWorkOrder(ServiceTestConsole.OPEXTSoapService.WorkOrderRequest workOrderInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportWorkOrder", ReplyAction="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportWorkOrderResponse")]
        System.Threading.Tasks.Task<ServiceTestConsole.OPEXTSoapService.WorkOrderResponse> ImportWorkOrderAsync(ServiceTestConsole.OPEXTSoapService.WorkOrderRequest workOrderInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportMaterialDefinition", ReplyAction="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportMaterialDefinitionResponse")]
        ServiceTestConsole.OPEXTSoapService.MaterialDefinitionResponse ImportMaterialDefinition(ServiceTestConsole.OPEXTSoapService.MaterialDefinitionRequest materialDefinition);
        
        [System.ServiceModel.OperationContractAttribute(Action="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportMaterialDefinition", ReplyAction="Engineering.DAB.UADMSoapWrap/IOPEXTWrapper/ImportMaterialDefinitionResponse")]
        System.Threading.Tasks.Task<ServiceTestConsole.OPEXTSoapService.MaterialDefinitionResponse> ImportMaterialDefinitionAsync(ServiceTestConsole.OPEXTSoapService.MaterialDefinitionRequest materialDefinition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOPEXTWrapperChannel : ServiceTestConsole.OPEXTSoapService.IOPEXTWrapper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OPEXTWrapperClient : System.ServiceModel.ClientBase<ServiceTestConsole.OPEXTSoapService.IOPEXTWrapper>, ServiceTestConsole.OPEXTSoapService.IOPEXTWrapper {
        
        public OPEXTWrapperClient() {
        }
        
        public OPEXTWrapperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OPEXTWrapperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OPEXTWrapperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OPEXTWrapperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceTestConsole.OPEXTSoapService.WorkOrderResponse ImportWorkOrder(ServiceTestConsole.OPEXTSoapService.WorkOrderRequest workOrderInfo) {
            return base.Channel.ImportWorkOrder(workOrderInfo);
        }
        
        public System.Threading.Tasks.Task<ServiceTestConsole.OPEXTSoapService.WorkOrderResponse> ImportWorkOrderAsync(ServiceTestConsole.OPEXTSoapService.WorkOrderRequest workOrderInfo) {
            return base.Channel.ImportWorkOrderAsync(workOrderInfo);
        }
        
        public ServiceTestConsole.OPEXTSoapService.MaterialDefinitionResponse ImportMaterialDefinition(ServiceTestConsole.OPEXTSoapService.MaterialDefinitionRequest materialDefinition) {
            return base.Channel.ImportMaterialDefinition(materialDefinition);
        }
        
        public System.Threading.Tasks.Task<ServiceTestConsole.OPEXTSoapService.MaterialDefinitionResponse> ImportMaterialDefinitionAsync(ServiceTestConsole.OPEXTSoapService.MaterialDefinitionRequest materialDefinition) {
            return base.Channel.ImportMaterialDefinitionAsync(materialDefinition);
        }
    }
}
